import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { ArrowLeft, BarChart3 } from "lucide-react";
import { psicoAdminService } from "@/features/psicosocial/api/psicoAdminService";

export default function AplicacionResultadosPage() {
  const { empresaId = "", aplicacionId = "" } = useParams();
  const navigate = useNavigate();
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { if (!empresaId || !aplicacionId) return; setLoading(true); psicoAdminService.resultadoAplicacion(empresaId, Number(aplicacionId)).then(setData).catch((e)=>setError(e.message)).finally(()=>setLoading(false)); }, [empresaId, aplicacionId]);
  return <main className="min-h-screen bg-slate-50 p-6 lg:p-8"><div className="mx-auto max-w-7xl space-y-6"><button onClick={()=>navigate(`/psicosocial/empresas/${empresaId}/aplicaciones`)} className="inline-flex items-center gap-2 rounded-xl border bg-white px-4 py-2 text-sm font-bold shadow-sm"><ArrowLeft className="h-4 w-4"/> Volver</button>{loading ? <p>Cargando resultados...</p> : error ? <div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-red-700">{error}</div> : <><section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-sm font-black uppercase text-violet-700">Resultado de aplicación</p><h1 className="text-3xl font-black">{data?.aplicacion?.nombre}</h1><p className="text-sm text-slate-500">Aplicación #{data?.aplicacion?.id} · {data?.aplicacion?.estado}</p></section><section className="grid gap-4 md:grid-cols-3">{(data?.resumen||[]).map((r:any)=><div key={`${r.instrument_code}-${r.total_code}`} className="rounded-2xl border bg-white p-5 shadow-sm"><BarChart3 className="mb-3 h-6 w-6 text-violet-700"/><h3 className="font-black">{r.instrument_code}</h3><p className="text-sm text-slate-500">{r.total_code}</p><p className="mt-3 text-2xl font-black">{r.promedio_transformado ?? "-"}</p><p className="text-xs text-slate-500">N {r.n} · Alto/Muy alto {r.alto_muy_alto}</p></div>)}</section><section className="rounded-3xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-black">Dimensiones críticas</h2><div className="mt-4 overflow-hidden rounded-2xl border"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Dimensión</th><th className="px-4 py-3">Dominio</th><th className="px-4 py-3">Instrumento</th><th className="px-4 py-3">Promedio</th><th className="px-4 py-3">Alto/Muy alto</th></tr></thead><tbody className="divide-y">{(data?.dimensiones||[]).map((d:any)=><tr key={`${d.instrument_code}-${d.dimension_code}`}><td className="px-4 py-3 font-bold">{d.dimension_code}</td><td className="px-4 py-3">{d.dominio_code}</td><td className="px-4 py-3">{d.instrument_code}</td><td className="px-4 py-3 font-black">{d.promedio_transformado}</td><td className="px-4 py-3">{d.alto_muy_alto}</td></tr>)}</tbody></table></div></section></>}</div></main>;
}
