// src/pages/superadmin/SuperAdminEmpresasPage.tsx
import { useEffect, useState } from "react";
import { Plus } from "lucide-react";
import { superadminService, type SuperEmpresa } from "@/features/superadmin/api/superadminService";
import SuperAdminPagination from "@/features/superadmin/components/SuperAdminPagination";
import SuperAdminPageHeader from "./SuperAdminPageHeader";

export default function SuperAdminEmpresasPage() {
  const [items, setItems] = useState<SuperEmpresa[]>([]); const [total, setTotal] = useState(0); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(10); const [q, setQ] = useState(""); const [error, setError] = useState<string | null>(null);
  useEffect(() => { superadminService.empresas({ q, page, page_size: pageSize }).then((r) => { setItems(r.items); setTotal(r.total); }).catch((e) => setError(e.message)); }, [q, page, pageSize]);
  return <div><SuperAdminPageHeader title="Empresas" subtitle="Gestiona y supervisa todas las empresas registradas." action={<button className="inline-flex items-center gap-2 rounded-2xl bg-violet-600 px-5 py-3 font-black text-white shadow-lg shadow-violet-200"><Plus className="h-5 w-5" /> Nueva empresa</button>} />{error && <div className="mb-5 rounded-2xl border border-red-200 bg-red-50 p-4 text-red-700">{error}</div>}<div className="rounded-3xl border bg-white shadow-sm"><div className="grid gap-4 p-5 md:grid-cols-[1fr_auto]"><input value={q} onChange={(e) => { setQ(e.target.value); setPage(1); }} className="h-12 rounded-2xl border border-slate-200 px-4" placeholder="Buscar por nombre, NIT o responsable..." /><button className="rounded-2xl border px-5 font-black">Filtros</button></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-4">Empresa</th><th>NIT</th><th>Empleados</th><th>Aplicaciones</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{items.map((e) => <tr key={e.id} className="border-t"><td className="px-5 py-4"><div className="font-black">{e.nombre}</div><div className="text-xs text-slate-500">{e.id}</div></td><td>{e.nit || "—"}</td><td>{e.empleados ?? 0}</td><td>{e.aplicaciones ?? 0}</td><td><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-black text-emerald-700">Activa</span></td><td><button className="rounded-xl border px-3 py-2 font-bold">Ver</button></td></tr>)}</tbody></table></div><SuperAdminPagination page={page} pageSize={pageSize} total={total} onPageChange={setPage} onPageSizeChange={(s) => { setPageSize(s); setPage(1); }} /></div></div>;
}
