// src/pages/superadmin/SuperAdminCreditosPage.tsx
import { useEffect, useState } from "react";
import { superadminService, type CreditAccount } from "@/features/superadmin/api/superadminService";
import SuperAdminPagination from "@/features/superadmin/components/SuperAdminPagination";
import SuperAdminPageHeader from "./SuperAdminPageHeader";

export default function SuperAdminCreditosPage() {
  const [items, setItems] = useState<CreditAccount[]>([]); const [total, setTotal] = useState(0); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(10); const [q, setQ] = useState(""); const [error, setError] = useState<string | null>(null);
  const load = () => superadminService.creditAccounts({ q, page, page_size: pageSize }).then((r) => { setItems(r.items); setTotal(r.total); }).catch((e) => setError(e.message));
  useEffect(() => { load(); }, [q, page, pageSize]);
  return <div><SuperAdminPageHeader title="Créditos" subtitle="Ledger formal: asignación, consumo y auditoría por psicólogo/empresa." action={<button className="rounded-2xl bg-violet-600 px-5 py-3 font-black text-white">Asignar créditos</button>} />{error && <div className="mb-5 rounded-2xl border border-red-200 bg-red-50 p-4 text-red-700">{error}</div>}<div className="rounded-3xl border bg-white shadow-sm"><div className="p-5"><input value={q} onChange={(e) => { setQ(e.target.value); setPage(1); }} className="h-12 w-full rounded-2xl border border-slate-200 px-4" placeholder="Buscar por psicólogo, correo o empresa..." /></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-4">Cuenta</th><th>Empresa</th><th>Asignados</th><th>Saldo</th><th>Estado</th><th>Actualizado</th></tr></thead><tbody>{items.map((c) => <tr key={c.id} className="border-t"><td className="px-5 py-4"><div className="font-black">{c.psicologo_nombre}</div><div className="text-xs text-slate-500">{c.psicologo_email}</div></td><td>{c.empresa_nombre || "Cuenta global"}</td><td>{c.creditos_asignados}</td><td><span className="font-black text-violet-700">{c.saldo_actual}</span></td><td><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-black text-emerald-700">{c.estado}</span></td><td>{c.actualizado_en ? new Date(c.actualizado_en).toLocaleString() : "—"}</td></tr>)}</tbody></table></div><SuperAdminPagination page={page} pageSize={pageSize} total={total} onPageChange={setPage} onPageSizeChange={(s) => { setPageSize(s); setPage(1); }} /></div></div>;
}
