import type { WebDirectInstrumentCode } from "./types";

// Textos de apoyo suministrados para facilitar la comprensión sin modificar el ítem oficial.
const QUESTION_NOTES: Record<WebDirectInstrumentCode, Record<number, string>> = {
  "PSICO_INTRA_A": {
    "1": "Piensa en tu lugar de trabajo habitual: en qué medida el ruido que hay allí puede resultarte incómodo mientras realizas tus tareas.",
    "2": "Piensa en cómo se siente normalmente la temperatura de tu lugar de trabajo y si con frecuencia percibes demasiado frío.",
    "3": "Piensa en cómo se siente normalmente la temperatura de tu lugar de trabajo y si con frecuencia percibes demasiado calor.",
    "4": "Piensa en el aire que respiras mientras trabajas y en si el ambiente suele sentirse fresco, ventilado y agradable.",
    "5": "Piensa en la iluminación que tienes para trabajar y en qué tan cómoda resulta para realizar tus actividades.",
    "6": "Piensa en el espacio físico donde realizas tus tareas y en si te permite trabajar con comodidad.",
    "7": "Piensa en si durante tu trabajo puedes estar en contacto con sustancias químicas y en la preocupación que eso puede generarte por tu salud.",
    "8": "Piensa en el esfuerzo que debe hacer tu cuerpo para cumplir con tus tareas habituales, como cargar, mover, empujar o mantener posturas exigentes.",
    "9": "Piensa en los equipos y herramientas que utilizas normalmente y en qué tan cómodos resultan para trabajar con ellos.",
    "10": "Piensa en si tu trabajo puede exponerte a microbios, animales o plantas y en la preocupación que esto puede generarte por tu salud.",
    "11": "Piensa en tu jornada habitual y en qué tanto te preocupa que pueda ocurrirte un accidente mientras trabajas.",
    "12": "Piensa en las condiciones habituales de tu lugar de trabajo, especialmente en qué tan limpio y organizado suele mantenerse.",
    "13": "Piensa en tu carga de trabajo habitual: si para alcanzar a cumplir con tus tareas necesitas quedarte trabajando más tiempo del establecido.",
    "14": "Piensa en un día normal de trabajo: si el tiempo de tu jornada suele ser suficiente para mantener tus tareas y responsabilidades al día.",
    "15": "Piensa en tu ritmo de trabajo y en si la cantidad de tareas te obliga a trabajar de manera continua, casi sin detenerte.",
    "16": "Piensa en cuánto necesitas analizar, razonar o mantener tu mente activa para poder realizar bien tu trabajo.",
    "17": "Piensa en cuánto tiempo necesitas mantener la atención y la concentración para poder cumplir adecuadamente con tus tareas.",
    "18": "Piensa en la cantidad de datos, instrucciones o información que necesitas recordar mientras realizas tu trabajo.",
    "19": "Piensa si en tu trabajo debes tomar decisiones importantes o difíciles teniendo muy poco tiempo para analizarlas.",
    "20": "Piensa si durante tu jornada debes ocuparte de varios asuntos, tareas o solicitudes al mismo tiempo.",
    "21": "Piensa en cuánto debes prestar atención a detalles pequeños para realizar correctamente tu trabajo o evitar errores.",
    "22": "Piensa si tu trabajo implica estar a cargo de equipos, materiales, productos u otros bienes que tienen un valor importante.",
    "23": "Piensa si dentro de tus funciones eres responsable de manejar, controlar o responder por dinero de la empresa.",
    "24": "Piensa si tus decisiones o acciones en el trabajo pueden afectar directamente la seguridad de otras personas.",
    "25": "Piensa si eres responsable, frente a tu jefe, por los resultados que obtiene todo un equipo, proceso o área de trabajo.",
    "26": "Piensa si dentro de tus funciones debes proteger, cuidar o tomar decisiones que puedan afectar la salud de otras personas.",
    "27": "Piensa si alguna vez recibes instrucciones diferentes o contrarias entre sí, de manera que no queda claro cuál debes seguir.",
    "28": "Piensa si te solicitan realizar actividades que, desde tu experiencia, parecen poco necesarias o no aportan realmente al trabajo.",
    "29": "Piensa si en tu trabajo aparecen situaciones en las que sientes presión para no seguir una norma o un procedimiento establecido.",
    "30": "Piensa si a veces debes realizar tareas de una manera complicada aunque consideres que podrían hacerse de forma más sencilla o práctica.",
    "31": "Piensa en tus horarios habituales y en con qué frecuencia debes trabajar durante la noche.",
    "32": "Piensa en tu jornada diaria y en si realmente tienes la posibilidad de hacer pequeñas pausas para descansar.",
    "33": "Piensa en con qué frecuencia tu trabajo ocupa días que normalmente serían de descanso, como fines de semana o festivos.",
    "34": "Piensa en un mes normal y en si cuentas con fines de semana o días libres que realmente puedas disfrutar como descanso.",
    "35": "Piensa en lo que ocurre cuando termina tu jornada: si tu mente continúa ocupada con pendientes, problemas o situaciones del trabajo cuando ya estás en casa.",
    "36": "Piensa si las situaciones, horarios o preocupaciones de tu trabajo han llegado a generar discusiones o dificultades con familiares o amigos.",
    "37": "Piensa si, aun estando en casa, debes responder llamadas, mensajes, pendientes u otras situaciones relacionadas con el trabajo.",
    "38": "Piensa en cuánto tiempo te deja realmente el trabajo para compartir y estar presente con tu familia y tus amigos.",
    "39": "Piensa si las actividades que realizas te permiten practicar, fortalecer y desarrollar las capacidades que tienes.",
    "40": "Piensa si tu trabajo te da la oportunidad de utilizar los conocimientos que ya has adquirido por estudio o experiencia.",
    "41": "Piensa si tu trabajo te permite descubrir, aprender o desarrollar conocimientos y habilidades nuevas.",
    "42": "Piensa si las tareas que te asignan suelen estar acordes con lo que sabes hacer y con las capacidades que tienes.",
    "43": "Piensa en un día normal de trabajo y en si puedes hacer una pausa cuando sientes que realmente la necesitas.",
    "44": "Piensa en cuánta libertad tienes para decidir la cantidad de trabajo que realizas durante tu jornada.",
    "45": "Piensa en si puedes ajustar el ritmo o la velocidad con la que realizas tus tareas, según las necesidades del trabajo.",
    "46": "Piensa en si puedes organizar por tu cuenta el orden en el que realizas las distintas actividades de tu trabajo.",
    "47": "Piensa si, cuando surge una necesidad personal, tienes la posibilidad de detenerte brevemente para atenderla.",
    "48": "Piensa en los cambios que has vivido en tu trabajo y en si, en general, han ayudado a que tu labor funcione mejor.",
    "49": "Piensa en cómo te comunican los cambios del trabajo y en si te explican de manera clara qué va a cambiar y por qué.",
    "50": "Piensa si tienes un espacio real para expresar ideas o sugerencias cuando van a realizar cambios que afectan tu trabajo.",
    "51": "Piensa si, cuando se hacen cambios en tu trabajo, tus ideas y sugerencias son escuchadas y consideradas.",
    "52": "Piensa si los cambios que se implementan terminan haciendo que tus tareas sean más difíciles de realizar.",
    "53": "Piensa si tienes claro qué tareas y responsabilidades te corresponden en tu cargo.",
    "54": "Piensa si sabes con claridad qué decisiones puedes tomar por tu cuenta dentro de tu trabajo.",
    "55": "Piensa si sabes cuáles son los resultados concretos que esperan de ti en tu trabajo.",
    "56": "Piensa si te han explicado de qué manera tu trabajo aporta o influye en lo que hace la empresa.",
    "57": "Piensa si tienes claros los objetivos principales que orientan el trabajo que realizas.",
    "58": "Piensa si sabes a quién acudir cuando necesitas orientación para saber cómo realizar correctamente una tarea.",
    "59": "Piensa si sabes con claridad con quién puedes hablar cuando necesitas resolver una situación o un asunto de trabajo.",
    "60": "Piensa si la empresa te da oportunidades reales de asistir a capacitaciones relacionadas con las funciones que realizas.",
    "61": "Piensa en las capacitaciones que recibes y en si lo aprendido te resulta útil para hacer tu trabajo.",
    "62": "Piensa si la capacitación que recibes te ayuda de manera práctica a desempeñar mejor tus tareas.",
    "63": "Piensa en las indicaciones de tu jefe y en si normalmente te permiten entender con claridad qué debes hacer.",
    "64": "Piensa en si tu jefe contribuye a ordenar prioridades, tareas y responsabilidades para que el trabajo pueda realizarse mejor.",
    "65": "Piensa en las conversaciones con tu jefe: cuando expresas una idea u opinión, si sientes que realmente es escuchada y tomada en cuenta.",
    "66": "Piensa en si tu jefe te motiva, reconoce tu esfuerzo o te impulsa a hacer cada vez mejor tu trabajo.",
    "67": "Piensa en la forma como tu jefe reparte las tareas y en si esa distribución facilita que puedas cumplir con tu trabajo.",
    "68": "Piensa en si tu jefe te comunica la información que necesitas con suficiente anticipación para poder actuar a tiempo.",
    "69": "Piensa en si las orientaciones de tu jefe te aclaran qué hacer y te ayudan a realizar mejor tus tareas.",
    "70": "Piensa si tu jefe te brinda orientación, oportunidades o apoyo que favorecen tu crecimiento dentro del trabajo.",
    "71": "Piensa en cómo te hace sentir la relación con tu jefe y en si su manera de liderar contribuye a que estés bien en el trabajo.",
    "72": "Piensa en los momentos en que surge un problema laboral y en si tu jefe participa activamente para ayudar a resolverlo.",
    "73": "Piensa en la relación cotidiana con tu jefe y en si sientes seguridad para confiar en él o ella en asuntos de trabajo.",
    "74": "Piensa en los momentos en que tienes una dificultad laboral y en si tu jefe te presta atención cuando se la cuentas.",
    "75": "Piensa en los momentos en que necesitas ayuda en el trabajo y en si sientes que puedes contar con el apoyo de tu jefe.",
    "76": "Piensa en cómo te sientes normalmente cuando compartes y trabajas con las personas de tu grupo.",
    "77": "Piensa en cómo te hablan y te tratan tus compañeros en el día a día, incluso cuando existen diferencias o momentos de tensión.",
    "78": "Piensa en la relación con tus compañeros y en si sientes que puedes confiar en ellos cuando se trata de asuntos de trabajo.",
    "79": "Piensa en qué tan cómodo o tranquilo te sientes al relacionarte y trabajar con tus compañeros.",
    "80": "Piensa si en tu grupo has vivido situaciones en las que alguien te haya tratado de una forma que sentiste ofensiva, humillante o irrespetuosa.",
    "81": "Piensa en cómo manejan los desacuerdos entre compañeros y en si pueden conversar y resolverlos manteniendo el respeto.",
    "82": "Piensa si las personas de tu equipo se sienten conectadas entre sí y participan como parte de un mismo grupo.",
    "83": "Piensa en qué tan cercana y colaborativa suele ser la relación entre las personas que conforman tu grupo de trabajo.",
    "84": "Piensa si, en tu día a día, las personas con las que trabajas te hacen sentir incluido y parte del equipo.",
    "85": "Piensa en lo que ocurre cuando deben trabajar juntos y en si tus compañeros realmente colaboran para sacar adelante la tarea.",
    "86": "Piensa en cómo toman decisiones como grupo y en qué tan fácil resulta llegar a acuerdos para poder trabajar.",
    "87": "Piensa en los momentos en que tienes una dificultad y en si tus compañeros están dispuestos a ayudarte.",
    "88": "Piensa en la dinámica cotidiana del trabajo y en si las personas acostumbran ayudarse y respaldarse entre sí.",
    "89": "Piensa si hay compañeros con quienes puedas hablar y sentirte escuchado cuando tienes algún problema.",
    "90": "Piensa si recibes información o comentarios que te permiten reconocer qué aspectos de tu trabajo estás haciendo bien.",
    "91": "Piensa si te dicen de manera concreta qué aspectos de tu trabajo necesitas ajustar o mejorar.",
    "92": "Piensa en los comentarios que recibes sobre tu desempeño y en si son suficientemente claros para que puedas comprenderlos.",
    "93": "Piensa si la manera como evalúan tu trabajo te deja orientaciones útiles que realmente te permiten mejorar.",
    "94": "Piensa si te comunican oportunamente aquello que debes mejorar, de modo que todavía puedas hacer cambios a tiempo.",
    "95": "Piensa en la manera como la empresa delega responsabilidades en ti y en si percibes que confía en tu capacidad para cumplirlas.",
    "96": "Piensa en si el pago de tu salario suele realizarse dentro de las fechas y tiempos que fueron acordados.",
    "97": "Piensa en si la remuneración que recibes corresponde a lo que la empresa te ofreció cuando acordaron las condiciones del trabajo.",
    "98": "Piensa en tu remuneración y en si sientes que corresponde al esfuerzo, responsabilidad y trabajo que realizas.",
    "99": "Piensa en si dentro de tu trabajo existen oportunidades reales para crecer, asumir nuevos retos o avanzar profesionalmente.",
    "100": "Piensa en si las personas que realizan bien su trabajo tienen oportunidades reales de crecer o progresar dentro de la empresa.",
    "101": "Piensa en las decisiones y acciones de la empresa y en si percibes un interés real por el bienestar de las personas que trabajan allí.",
    "102": "Piensa en qué tan seguro o estable sientes tu trabajo y en si percibes continuidad en tu vínculo con la empresa.",
    "103": "Piensa en cómo te hace sentir el trabajo que realizas habitualmente y en la satisfacción personal que puede producirte hacerlo.",
    "104": "Piensa en cómo te sientes cuando dices que trabajas en esta empresa y en lo que significa para ti pertenecer a ella.",
    "105": "Piensa en la manera como hablas de la empresa fuera del trabajo y en si normalmente expresas cosas positivas sobre ella.",
    "106": "Piensa en las personas que atiendes normalmente y en con qué frecuencia debes tratar con alguien que llega muy molesto o enojado.",
    "107": "Piensa en las personas que atiendes y en con qué frecuencia debes acompañar o responder a alguien que se encuentra muy preocupado o angustiado.",
    "108": "Piensa en las personas que atiendes y en con qué frecuencia debes interactuar con alguien que se encuentra muy triste.",
    "109": "Piensa si dentro de tu trabajo debes atender o acompañar a personas que presentan enfermedades importantes o delicadas.",
    "110": "Piensa si tu trabajo implica atender personas que necesitan mucha ayuda, orientación o apoyo.",
    "111": "Piensa si, al atender clientes o usuarios, has debido enfrentar insultos, agresiones verbales u otras formas de trato irrespetuoso.",
    "112": "Piensa si en tu trabajo algunas veces necesitas mostrar calma, amabilidad u otra emoción aunque por dentro estés sintiendo algo diferente.",
    "113": "Piensa si tu trabajo te lleva a presenciar, atender o intervenir en situaciones donde hay agresiones o violencia.",
    "114": "Piensa si tu trabajo te expone a historias, situaciones o experiencias que pueden ser emocionalmente muy dolorosas o tristes.",
    "115": "Piensa en las personas que supervisas y en si suelen comunicar temas importantes cuando ya ha pasado el momento oportuno para hacerlo.",
    "116": "Piensa en la manera como se relacionan contigo las personas que supervisas y en si algunas veces utilizan formas de trato irrespetuosas.",
    "117": "Piensa si ciertas conductas de las personas que supervisas hacen más difícil organizar tareas, tiempos o responsabilidades del equipo.",
    "118": "Piensa en los momentos en que pides la opinión de tus colaboradores y en si algunos prefieren no expresar lo que piensan.",
    "119": "Piensa si el comportamiento o la forma de trabajar de algunos colaboradores dificulta que el equipo alcance los resultados esperados.",
    "120": "Piensa en cómo expresan sus desacuerdos las personas que supervisas y en si algunas veces lo hacen de una manera irrespetuosa.",
    "121": "Piensa en las situaciones que requieren apoyo del equipo y en si algunos colaboradores participan o cooperan menos de lo necesario.",
    "122": "Piensa en el desempeño de las personas que supervisas y en si hay casos que te generan preocupación por la manera como están trabajando.",
    "123": "Piensa en si algunos colaboradores reciben recomendaciones para mejorar, pero aun así suelen ignorarlas o no ponerlas en práctica."
  },
  "PSICO_INTRA_B": {
    "1": "Piensa en tu lugar de trabajo habitual: en qué medida el ruido que hay allí puede resultarte incómodo mientras realizas tus tareas.",
    "2": "Piensa en cómo se siente normalmente la temperatura de tu lugar de trabajo y si con frecuencia percibes demasiado frío.",
    "3": "Piensa en cómo se siente normalmente la temperatura de tu lugar de trabajo y si con frecuencia percibes demasiado calor.",
    "4": "Piensa en el aire que respiras mientras trabajas y en si el ambiente suele sentirse fresco, ventilado y agradable.",
    "5": "Piensa en la iluminación que tienes para trabajar y en qué tan cómoda resulta para realizar tus actividades.",
    "6": "Piensa en el espacio físico donde realizas tus tareas y en si te permite trabajar con comodidad.",
    "7": "Piensa en si durante tu trabajo puedes estar en contacto con sustancias químicas y en la preocupación que eso puede generarte por tu salud.",
    "8": "Piensa en el esfuerzo que debe hacer tu cuerpo para cumplir con tus tareas habituales, como cargar, mover, empujar o mantener posturas exigentes.",
    "9": "Piensa en los equipos y herramientas que utilizas normalmente y en qué tan cómodos resultan para trabajar con ellos.",
    "10": "Piensa en si tu trabajo puede exponerte a microbios, animales o plantas y en la preocupación que esto puede generarte por tu salud.",
    "11": "Piensa en tu jornada habitual y en qué tanto te preocupa que pueda ocurrirte un accidente mientras trabajas.",
    "12": "Piensa en las condiciones habituales de tu lugar de trabajo, especialmente en qué tan limpio y organizado suele mantenerse.",
    "13": "Piensa en tu carga de trabajo habitual: si para alcanzar a cumplir con tus tareas necesitas quedarte trabajando más tiempo del establecido.",
    "14": "Piensa en un día normal de trabajo: si el tiempo de tu jornada suele ser suficiente para mantener tus tareas y responsabilidades al día.",
    "15": "Piensa en tu ritmo de trabajo y en si la cantidad de tareas te obliga a trabajar de manera continua, casi sin detenerte.",
    "16": "Piensa en cuánto necesitas analizar, razonar o mantener tu mente activa para poder realizar bien tu trabajo.",
    "17": "Piensa en cuánto tiempo necesitas mantener la atención y la concentración para poder cumplir adecuadamente con tus tareas.",
    "18": "Piensa en la cantidad de datos, instrucciones o información que necesitas recordar mientras realizas tu trabajo.",
    "19": "Piensa si tus tareas habituales requieren que hagas operaciones, cuentas o cálculos numéricos para poder realizarlas correctamente.",
    "20": "Piensa en cuánto debes prestar atención a detalles pequeños para realizar correctamente tu trabajo o evitar errores.",
    "21": "Piensa en tus horarios habituales y en con qué frecuencia debes trabajar durante la noche.",
    "22": "Piensa en tu jornada diaria y en si realmente tienes la posibilidad de hacer pequeñas pausas para descansar.",
    "23": "Piensa en con qué frecuencia tu trabajo ocupa días que normalmente serían de descanso, como fines de semana o festivos.",
    "24": "Piensa en un mes normal y en si cuentas con fines de semana o días libres que realmente puedas disfrutar como descanso.",
    "25": "Piensa en lo que ocurre cuando termina tu jornada: si tu mente continúa ocupada con pendientes, problemas o situaciones del trabajo cuando ya estás en casa.",
    "26": "Piensa si las situaciones, horarios o preocupaciones de tu trabajo han llegado a generar discusiones o dificultades con familiares o amigos.",
    "27": "Piensa si, aun estando en casa, debes responder llamadas, mensajes, pendientes u otras situaciones relacionadas con el trabajo.",
    "28": "Piensa en cuánto tiempo te deja realmente el trabajo para compartir y estar presente con tu familia y tus amigos.",
    "29": "Piensa si tu trabajo te permite salir de la rutina y realizar actividades nuevas o diferentes a las que haces habitualmente.",
    "30": "Piensa si las actividades que realizas te permiten practicar, fortalecer y desarrollar las capacidades que tienes.",
    "31": "Piensa si tu trabajo te da la oportunidad de utilizar los conocimientos que ya has adquirido por estudio o experiencia.",
    "32": "Piensa si tu trabajo te permite descubrir, aprender o desarrollar conocimientos y habilidades nuevas.",
    "33": "Piensa en un día normal de trabajo y en si puedes hacer una pausa cuando sientes que realmente la necesitas.",
    "34": "Piensa en cuánta libertad tienes para decidir la cantidad de trabajo que realizas durante tu jornada.",
    "35": "Piensa en si puedes ajustar el ritmo o la velocidad con la que realizas tus tareas, según las necesidades del trabajo.",
    "36": "Piensa en si puedes organizar por tu cuenta el orden en el que realizas las distintas actividades de tu trabajo.",
    "37": "Piensa si, cuando surge una necesidad personal, tienes la posibilidad de detenerte brevemente para atenderla.",
    "38": "Piensa en cómo te comunican los cambios del trabajo y en si te explican de manera clara qué va a cambiar y por qué.",
    "39": "Piensa si tienes un espacio real para expresar ideas o sugerencias cuando van a realizar cambios que afectan tu trabajo.",
    "40": "Piensa si, cuando se hacen cambios en tu trabajo, tus ideas y sugerencias son escuchadas y consideradas.",
    "41": "Piensa si tienes claro qué tareas y responsabilidades te corresponden en tu cargo.",
    "42": "Piensa si sabes con claridad qué decisiones puedes tomar por tu cuenta dentro de tu trabajo.",
    "43": "Piensa si sabes cuáles son los resultados concretos que esperan de ti en tu trabajo.",
    "44": "Piensa si tienes claros los objetivos principales que orientan el trabajo que realizas.",
    "45": "Piensa si sabes con claridad con quién puedes hablar cuando necesitas resolver una situación o un asunto de trabajo.",
    "46": "Piensa si la empresa te da oportunidades reales de asistir a capacitaciones relacionadas con las funciones que realizas.",
    "47": "Piensa en las capacitaciones que recibes y en si lo aprendido te resulta útil para hacer tu trabajo.",
    "48": "Piensa si la capacitación que recibes te ayuda de manera práctica a desempeñar mejor tus tareas.",
    "49": "Piensa en si tu jefe contribuye a ordenar prioridades, tareas y responsabilidades para que el trabajo pueda realizarse mejor.",
    "50": "Piensa en las conversaciones con tu jefe: cuando expresas una idea u opinión, si sientes que realmente es escuchada y tomada en cuenta.",
    "51": "Piensa en si tu jefe te motiva, reconoce tu esfuerzo o te impulsa a hacer cada vez mejor tu trabajo.",
    "52": "Piensa en la forma como tu jefe reparte las tareas y en si esa distribución facilita que puedas cumplir con tu trabajo.",
    "53": "Piensa en si tu jefe te comunica la información que necesitas con suficiente anticipación para poder actuar a tiempo.",
    "54": "Piensa en si las orientaciones de tu jefe te aclaran qué hacer y te ayudan a realizar mejor tus tareas.",
    "55": "Piensa si tu jefe te brinda orientación, oportunidades o apoyo que favorecen tu crecimiento dentro del trabajo.",
    "56": "Piensa en cómo te hace sentir la relación con tu jefe y en si su manera de liderar contribuye a que estés bien en el trabajo.",
    "57": "Piensa en los momentos en que surge un problema laboral y en si tu jefe participa activamente para ayudar a resolverlo.",
    "58": "Piensa en la forma como tu jefe se dirige a ti y te trata en el día a día, incluso cuando existen diferencias o momentos difíciles.",
    "59": "Piensa en la relación cotidiana con tu jefe y en si sientes seguridad para confiar en él o ella en asuntos de trabajo.",
    "60": "Piensa en los momentos en que tienes una dificultad laboral y en si tu jefe te presta atención cuando se la cuentas.",
    "61": "Piensa en los momentos en que necesitas ayuda en el trabajo y en si sientes que puedes contar con el apoyo de tu jefe.",
    "62": "Piensa en cómo te sientes normalmente cuando compartes y trabajas con las personas de tu grupo.",
    "63": "Piensa en cómo te hablan y te tratan tus compañeros en el día a día, incluso cuando existen diferencias o momentos de tensión.",
    "64": "Piensa en la relación con tus compañeros y en si sientes que puedes confiar en ellos cuando se trata de asuntos de trabajo.",
    "65": "Piensa en qué tan cómodo o tranquilo te sientes al relacionarte y trabajar con tus compañeros.",
    "66": "Piensa si en tu grupo has vivido situaciones en las que alguien te haya tratado de una forma que sentiste ofensiva, humillante o irrespetuosa.",
    "67": "Piensa en cómo manejan los desacuerdos entre compañeros y en si pueden conversar y resolverlos manteniendo el respeto.",
    "68": "Piensa en qué tan cercana y colaborativa suele ser la relación entre las personas que conforman tu grupo de trabajo.",
    "69": "Piensa en lo que ocurre cuando deben trabajar juntos y en si tus compañeros realmente colaboran para sacar adelante la tarea.",
    "70": "Piensa en cómo toman decisiones como grupo y en qué tan fácil resulta llegar a acuerdos para poder trabajar.",
    "71": "Piensa en los momentos en que tienes una dificultad y en si tus compañeros están dispuestos a ayudarte.",
    "72": "Piensa en la dinámica cotidiana del trabajo y en si las personas acostumbran ayudarse y respaldarse entre sí.",
    "73": "Piensa si hay compañeros con quienes puedas hablar y sentirte escuchado cuando tienes algún problema.",
    "74": "Piensa si recibes información o comentarios que te permiten reconocer qué aspectos de tu trabajo estás haciendo bien.",
    "75": "Piensa si te dicen de manera concreta qué aspectos de tu trabajo necesitas ajustar o mejorar.",
    "76": "Piensa en los comentarios que recibes sobre tu desempeño y en si son suficientemente claros para que puedas comprenderlos.",
    "77": "Piensa si la manera como evalúan tu trabajo te deja orientaciones útiles que realmente te permiten mejorar.",
    "78": "Piensa si te comunican oportunamente aquello que debes mejorar, de modo que todavía puedas hacer cambios a tiempo.",
    "79": "Piensa en si el pago de tu salario suele realizarse dentro de las fechas y tiempos que fueron acordados.",
    "80": "Piensa en si la remuneración que recibes corresponde a lo que la empresa te ofreció cuando acordaron las condiciones del trabajo.",
    "81": "Piensa en tu remuneración y en si sientes que corresponde al esfuerzo, responsabilidad y trabajo que realizas.",
    "82": "Piensa en si dentro de tu trabajo existen oportunidades reales para crecer, asumir nuevos retos o avanzar profesionalmente.",
    "83": "Piensa en si las personas que realizan bien su trabajo tienen oportunidades reales de crecer o progresar dentro de la empresa.",
    "84": "Piensa en las decisiones y acciones de la empresa y en si percibes un interés real por el bienestar de las personas que trabajan allí.",
    "85": "Piensa en qué tan seguro o estable sientes tu trabajo y en si percibes continuidad en tu vínculo con la empresa.",
    "86": "Piensa en cómo te hace sentir el trabajo que realizas habitualmente y en la satisfacción personal que puede producirte hacerlo.",
    "87": "Piensa en cómo te sientes cuando dices que trabajas en esta empresa y en lo que significa para ti pertenecer a ella.",
    "88": "Piensa en la manera como hablas de la empresa fuera del trabajo y en si normalmente expresas cosas positivas sobre ella.",
    "89": "Piensa en las personas que atiendes normalmente y en con qué frecuencia debes tratar con alguien que llega muy molesto o enojado.",
    "90": "Piensa en las personas que atiendes y en con qué frecuencia debes acompañar o responder a alguien que se encuentra muy preocupado o angustiado.",
    "91": "Piensa en las personas que atiendes y en con qué frecuencia debes interactuar con alguien que se encuentra muy triste.",
    "92": "Piensa si dentro de tu trabajo debes atender o acompañar a personas que presentan enfermedades importantes o delicadas.",
    "93": "Piensa si tu trabajo implica atender personas que necesitan mucha ayuda, orientación o apoyo.",
    "94": "Piensa si, al atender clientes o usuarios, has debido enfrentar insultos, agresiones verbales u otras formas de trato irrespetuoso.",
    "95": "Piensa si tu trabajo te lleva a presenciar, atender o intervenir en situaciones donde hay agresiones o violencia.",
    "96": "Piensa si tu trabajo te expone a historias, situaciones o experiencias que pueden ser emocionalmente muy dolorosas o tristes.",
    "97": "Piensa si, cuando atiendes a otras personas, puedes mostrar de manera natural que estás triste o enojado sin tener que ocultarlo por tu trabajo."
  },
  "PSICO_EXTRA": {
    "1": "Piensa en tu recorrido habitual entre la casa y el trabajo y en qué tan sencillo te resulta hacer ese trayecto.",
    "2": "Piensa en tu viaje diario al trabajo y en si necesitas combinar varios buses, rutas u otros medios para poder llegar.",
    "3": "Piensa en cuánto tiempo de tu día ocupas normalmente desplazándote entre tu casa y el trabajo, contando la ida y el regreso.",
    "4": "Piensa en cómo realizas normalmente el trayecto entre tu casa y el trabajo y en qué tan cómodo te resulta ese desplazamiento.",
    "5": "Piensa en el lugar donde vives y en qué tan tranquilo te sientes al caminar, salir o permanecer allí.",
    "6": "Piensa en lo que ocurre habitualmente en la zona donde vives y en la presencia de robos u otras situaciones de delincuencia.",
    "7": "Piensa en qué tan sencillo te resulta desplazarte desde tu vivienda hasta el centro médico donde recibes atención cuando la necesitas.",
    "8": "Piensa en las calles y vías cercanas a tu vivienda y en el estado en que normalmente se encuentran para transitar por ellas.",
    "9": "Piensa en tu zona de residencia y en qué tan fácil es encontrar transporte cuando necesitas movilizarte.",
    "10": "Piensa en tu vivienda en general y en si sus condiciones te parecen adecuadas para tus necesidades cotidianas.",
    "11": "Piensa en si tu vivienda cuenta de manera habitual con servicios básicos como agua y energía eléctrica.",
    "12": "Piensa en tu vivienda y en si allí puedes descansar con tranquilidad cuando tu cuerpo o tu mente lo necesitan.",
    "13": "Piensa en cómo te sientes estando en tu vivienda y en si el espacio te resulta cómodo para vivir.",
    "14": "Piensa en una semana habitual y en si dispones de tiempo para hacer actividades que disfrutas, te distraen o te ayudan a despejarte.",
    "15": "Piensa en tu rutina diaria y en si realmente cuentas con el tiempo que necesitas para dormir, recuperarte y descansar.",
    "16": "Piensa en si tus horarios y responsabilidades de trabajo te dejan tiempo disponible para atender asuntos personales y familiares.",
    "17": "Piensa en tu vida cotidiana y en si puedes dedicar tiempo de calidad a compartir con familiares o amigos.",
    "18": "Piensa en cómo suelen ser las conversaciones con las personas cercanas a ti y en si pueden comunicarse de una manera abierta y comprensible.",
    "19": "Piensa en la relación que mantienes con tus amigos y en qué tan positiva y agradable suele ser para ti.",
    "20": "Piensa en si tienes personas cercanas con quienes puedas conversar con naturalidad sobre distintos temas de tu vida.",
    "21": "Piensa en los momentos en que tienes una dificultad y en si tus amigos están disponibles para escucharte.",
    "22": "Piensa en los momentos difíciles y en si sientes que puedes contar con el apoyo de tu familia.",
    "23": "Piensa en si tienes personas de confianza con quienes puedas hablar sobre lo que te ocurre, lo que sientes o las situaciones que estás viviendo.",
    "24": "Piensa si las preocupaciones o dificultades de tu vida personal o familiar llegan a influir en la manera como realizas tu trabajo.",
    "25": "Piensa en la relación cotidiana con tu familia cercana y en si normalmente existe un trato amable y respetuoso.",
    "26": "Piensa si los problemas personales o familiares llegan a agotarte al punto de dejarte con menos energía para cumplir con tu trabajo.",
    "27": "Piensa en cómo suelen manejar en tu familia los desacuerdos o problemas y en si logran resolverlos mediante el diálogo y un trato respetuoso.",
    "28": "Piensa si las situaciones personales o familiares llegan a cambiar la forma como te relacionas con compañeros, jefes u otras personas en el trabajo.",
    "29": "Piensa en los ingresos que recibe tu hogar y en si normalmente permiten cubrir necesidades básicas como alimentación, vivienda, servicios y transporte.",
    "30": "Piensa si existen pagos u obligaciones económicas adicionales que reducen de manera importante el dinero disponible para los gastos del hogar.",
    "31": "Piensa en las deudas de tu hogar y en si algunas resultan difíciles de cubrir o pagar con los ingresos disponibles."
  },
  "PSICO_ESTRES": {
    "1": "Piensa en los últimos tres meses y en si has sentido dolor, rigidez o tensión en el cuello, la espalda o los músculos.",
    "2": "Piensa en los últimos tres meses y en si has tenido molestias frecuentes del estómago o la digestión, como acidez, dolor o problemas intestinales.",
    "3": "Piensa en los últimos tres meses y en si has presentado molestias o dificultades para respirar que hayan llamado tu atención.",
    "4": "Piensa en los últimos tres meses y en con qué frecuencia has tenido dolores de cabeza.",
    "5": "Piensa en los últimos tres meses y en si tu sueño ha cambiado, por ejemplo porque te cuesta dormir en la noche o sientes demasiado sueño durante el día.",
    "6": "Piensa en los últimos tres meses y en si has sentido palpitaciones, latidos fuertes o alguna molestia relacionada con el corazón.",
    "7": "Piensa en los últimos tres meses y en si has notado cambios importantes en tus ganas de comer, ya sea aumentando o disminuyendo tu apetito.",
    "8": "Piensa en los últimos tres meses y en si has notado dificultades o cambios importantes relacionados con tu respuesta o funcionamiento sexual.",
    "9": "Piensa en los últimos tres meses y en si te ha resultado más difícil relacionarte, conversar o llevarte bien con tu familia.",
    "10": "Piensa en los últimos tres meses y en si te ha costado estar tranquilo o, por el contrario, comenzar las actividades que necesitas realizar.",
    "11": "Piensa en los últimos tres meses y en si has tenido más dificultades de lo habitual para relacionarte o sentirte cómodo con otras personas.",
    "12": "Piensa en los últimos tres meses y en si has sentido ganas de alejarte de los demás o poco interés por personas y actividades que normalmente forman parte de tu vida.",
    "13": "Piensa en los últimos tres meses y en si has sentido que la cantidad o las exigencias de tu trabajo son mayores de lo que puedes manejar con tranquilidad.",
    "14": "Piensa en los últimos tres meses y en si te ha costado mantener la atención o recordar cosas que normalmente recordarías.",
    "15": "Piensa en los últimos tres meses y en si has notado que has tenido más accidentes o incidentes en el trabajo de lo habitual.",
    "16": "Piensa en los últimos tres meses y en si has sentido frustración al comparar lo que querías para tu vida con lo que has podido realizar hasta ahora.",
    "17": "Piensa en los últimos tres meses y en si has sentido cansancio frecuente, aburrimiento o pocas ganas de hacer tus actividades habituales.",
    "18": "Piensa en los últimos tres meses y en si has notado que te cuesta rendir como antes en el trabajo o encontrar ideas y soluciones con la misma facilidad.",
    "19": "Piensa en los últimos tres meses y en si has sentido ganas de evitar, aplazar o no asistir a tu trabajo.",
    "20": "Piensa en los últimos tres meses y en si has sentido menos interés, motivación o compromiso con las actividades que realizas.",
    "21": "Piensa en los últimos tres meses y en si tomar decisiones, incluso sobre asuntos cotidianos, te ha resultado más difícil de lo habitual.",
    "22": "Piensa en los últimos tres meses y en si has tenido con frecuencia el deseo de dejar tu empleo actual y buscar otro trabajo.",
    "23": "Piensa en los últimos tres meses y en si has experimentado sentimientos de soledad o miedo.",
    "24": "Piensa en los últimos tres meses y en si te has sentido más irritable, negativo o con menor tolerancia frente a situaciones cotidianas.",
    "25": "Piensa en los últimos tres meses y en si has sentido con frecuencia angustia, preocupación o tristeza.",
    "26": "Piensa en los últimos tres meses y en si has recurrido al consumo de alguna droga con la intención de disminuir la tensión o calmar los nervios.",
    "27": "Piensa en los últimos tres meses y en si has tenido pensamientos o sentimientos en los que te dices que \"no vales\" o que \"no sirves para nada\".",
    "28": "Piensa en los últimos tres meses y en con qué frecuencia has consumido bebidas alcohólicas, café o cigarrillo.",
    "29": "Piensa en los últimos tres meses y en si has llegado a sentir que \"estás perdiendo la razón\" o que no puedes comprender bien lo que te está pasando.",
    "30": "Piensa en los últimos tres meses y en si te has notado más inflexible, terco o aferrado a una forma de pensar o actuar, incluso cuando la situación requiere adaptarse.",
    "31": "Piensa en los últimos tres meses y en si has sentido que los problemas cotidianos o importantes de tu vida superan tu capacidad para afrontarlos."
  }
};

export function getWebDirectQuestionNote(
  instrumentCode: WebDirectInstrumentCode,
  order: number,
): string | null {
  return QUESTION_NOTES[instrumentCode][order] ?? null;
}
